# Generated by Django 3.2 on 2022-08-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classinfo', to='classes.classinfo'),
        ),
    ]
